# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01490a20fc79ac897195494aef225cb6f400eda3b69e900b2591e5afcc844fb124e429ff5293e27fd6d1b633ff6ef7f5e3c39e02bde085c53c29331d0fd80501

test:
  secret_key_base: 3d98ec541d1c1aa113bd8e3f187dd862af3ca3303691838f32772d080124fd0134f51e232949a87d020946425b267c3679ffa75dad4720f64de2e9d9b188d39d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
